services:
  local_web:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    image: api_bus:latest
    ports:
      - 8080:8080
    networks:
      - spring-network
networks:
  spring-network:
    driver: bridge