name: Update ConfigMap and Deploy

on:
  workflow_dispatch:

jobs:
  update-configmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for Existing SSH Tunnel
        run: |
          # Check if the SSH tunnel process is already running
          if lsof -i :6444; then
            echo "Existing SSH tunnel found on port 6444. Killing process..."
            lsof -ti :6444 | xargs kill -9
          else
            echo "No existing SSH tunnel found on port 6444."
          fi

      - name: Set up SSH Tunnel
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key -L 6444:localhost:6443 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p${{ secrets.SSH_PORT }} -N -f
            echo "SSH Tunnel established"

      - name: Test SSH Tunnel
        run: |
          curl -k https://localhost:6444/version

      - name: Configure kubeconfig
        run: |
          kubectl config set-cluster kubernetes --server=https://localhost:6444
          kubectl config set-credentials kubernetes-admin --client-certificate=/path/to/client.crt --client-key=/path/to/client.key
          kubectl config set-context kubernetes-admin@kubernetes --cluster=kubernetes --user=kubernetes-admin
          kubectl config use-context kubernetes-admin@kubernetes

      - name: Test Kubernetes Connection
        run: kubectl cluster-info

      - name: Update ConfigMap with Latest Tag
        run: |
          IMAGE_TAG=$(curl -s https://api.github.com/repos/wsb-cw8/co-Development-Task/releases/latest | jq -r .tag_name)
          kubectl -n default set env configmap/env IMAGE_TAG=${IMAGE_TAG}

      - name: Rollout the Deployment
        run: |
          kubectl rollout restart deployment/co-dev-task -n default

      - name: Clean Up SSH Tunnel
        if: always()
        run: |
          echo "Cleaning up SSH tunnel..."
          if lsof -i :6444; then
            lsof -ti :6444 | xargs kill -9
            echo "SSH tunnel process killed."
          else
            echo "No SSH tunnel process found to clean up."
          fi
