name: Update ConfigMap and Deploy

on:
  workflow_dispatch:

jobs:
  update-configmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute Kubernetes Commands via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Running kubectl commands on remote server..."

            # Get the latest release tag from GitHub
            IMAGE_TAG=$(curl -s https://api.github.com/repos/wsb-cw8/co-Development-Task/releases/latest | jq -r .tag_name)
            echo "Using image tag: ${IMAGE_TAG}"

            # Update the ConfigMap with the latest tag
            kubectl -n default set env configmap/env IMAGE_TAG=${IMAGE_TAG}

            # Restart the deployment to apply changes
            kubectl rollout restart deployment/co-dev-task -n default
