name: Update ConfigMap and Deploy

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  update-configmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH tunnel
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_key
            chmod 600 /tmp/ssh_key

            # Establish the SSH tunnel for port forwarding
            ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key -L 6444:localhost:6443 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p${{secrets.SSH_PORT}} -N -f
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.31.0'

      - name: Update ConfigMap with Latest Tag
        run: |
          # Get the latest release tag from GitHub
          IMAGE_TAG=$(curl -s https://api.github.com/repos/wsb-cw8/co-Development-Task/releases/latest | jq -r .tag_name)
          
          # Update the Kubernetes ConfigMap
          kubectl -n default set env configmap/env IMAGE_TAG=${IMAGE_TAG}

      - name: Rollout the Deployment
        run: |
          kubectl rollout restart deployment/co-dev-task -n default