name: BE Build and Push Docker Image

on:
  release:
    types:
      - created  # Trigger on release creation

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: ./api
        run: |
          # Get the release tag directly from the event
          IMAGE_TAG=${{ github.event.release.tag_name }}-be
          
          # Build the Docker image and tag it with the release tag
          docker build -t ghcr.io/wsb-cw8/co-development-task-be:${IMAGE_TAG} .
          docker tag ghcr.io/wsb-cw8/co-development-task-be:${IMAGE_TAG} ghcr.io/wsb-cw8/co-development-task:latest

      - name: Push Docker Image
        working-directory: ./api
        run: |
          IMAGE_TAG=${{ github.event.release.tag_name }}-be
          
          # Push the Docker image with both the release tag and the latest tag
          docker push ghcr.io/wsb-cw8/co-development-task-be:${IMAGE_TAG}
          docker push ghcr.io/wsb-cw8/co-development-task-be:latest
