name: FE Build and Push Docker Image

on:
  release:
    types:
      - created  # Trigger on release creation

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Retrieve Release Metadata
        id: get-release
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.payload.release.tag_name,
            });
            if (!release) {
              core.setFailed("No release found.");
              return;
            }
            core.setOutput("release-title", release.data.name.replace(/\s+/g, '-').toLowerCase());
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: ./fe
        run: |
          IMAGE_TAG=${{ steps.get-release.outputs.release-title }}
          docker build -t ghcr.io/wsb-cw8/co-development-task-fe:${IMAGE_TAG} .
          docker tag ghcr.io/wsb-cw8/co-development-task-fe:${IMAGE_TAG} ghcr.io/wsb-cw8/co-development-task-fe:latest

      - name: Push Docker Image
        working-directory: ./fe
        run: |
          IMAGE_TAG=${{ steps.get-release.outputs.release-title }}
          docker push ghcr.io/wsb-cw8/co-development-task-fe:${IMAGE_TAG}
          docker push ghcr.io/wsb-cw8/co-development-task-fe:latest
